galaxy_info:
  role_name: run_scap_scan
  author: Mike SUzadail
  description: SCAP Scan for Red Hat Enterprise Linux 7
  company: "Red Hat, Inc."

  issue_tracker_url:  https://github.com/msuzadail/run_scap_report/issues

  license: BSD-3-Clause

  min_ansible_version: 2.5

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
  - system
  - hardening
  - openscap
  - ssg
  - scap

dependencies: []
